<?php

namespace App\Http\Livewire\Campaigns;

use App\Http\Livewire\FormMain;
use App\Models\Campaign;

class Form extends FormMain
{
    protected $model = Campaign::class;

    public $props = [
        'name' => null,
        'products' => null,
        'is_active' => null,
    ];

    protected function rules(): array
    {
        return [
            'props.name' => ['required', 'string'],
        ];
    }

    public function mount($params = [])
    {
        parent::mount($params); // TODO: Change the autogenerated stub
        $this->setTitle(__('Create', ['name' => __('Campaign')]));

        if ($id = request()->route('campaign')) {
            $this->setEditing($id);
            $this->setTitle(__('Edit', ['name' => __('Campaign') . ' : ' . $this->editing->name]));
        }
    }

    protected function validationAttributes(): array
    {
        return [
            'props.name' => __('Name')
        ];
    }

    protected function saveAndRedirect($route = '')
    {
        $route = 'campaigns.index';
        parent::saveAndRedirect($route); // TODO: Change the autogenerated stub
    }

    public function render()
    {
        return view('livewire.campaigns.form');
    }
}
