<?php

namespace App\Http\Livewire\Profile;

use App\Enums\UserTypeEnum;
use App\Http\Livewire\FormMain;
use App\Models\City;
use App\Models\User;
use Illuminate\Validation\Rule;
use Livewire\WithFileUploads;

class GeneralForm extends FormMain
{
    use WithFileUploads;

    public $model = User::class;
    public $props = [
        'id' => null,
        'f_name' => null,
        'l_name' => null,
        'email' => null,
        'phone' => null,
        'dob' => null,
        'city_id' => null,
        'address' => null,
        'is_fingerprint_active' => null,
    ];
    public $files = [
        'profile_photo_path' => null
    ];

    public $mode = 'static';

    protected function rules(): array
    {

        return ($this->mode == 'defer') ? [
            'props.f_name' => [
                'required',
                'string',
            ],
            'props.l_name' => [
                'required',
                'string',
            ],
            'props.email' => [
                'required',
                'email',
                Rule::unique((new $this->model)->getTable(), 'email')->whereNull('deleted_at')->ignore($this->editing->id ?? ":id")
            ],
            'props.dob' => [
                'required',
                'date'
            ],
            'props.phone' => [
                'required',
                Rule::unique((new $this->model)->getTable(), 'phone')->whereNull('deleted_at')->ignore($this->editing->id ?? ":id")
            ],
            'props.city_id' => [
                'nullable',
                'integer',
                'exists:cities,id'
            ],
        ] : [
            'props.is_fingerprint_active' => ['nullable']
        ];
    }

    public function mount($params = [])
    {
        parent::mount($params); // TODO: Change the autogenerated stub
        $this->editing = auth()->user();
        $this->fillEditingProps();
    }

    protected function saveAndRedirect($route = '')
    {
        $route = 'self';
        parent::saveAndRedirect($route); // TODO: Change the autogenerated stub
    }

    public function render()
    {
        return view('livewire.profile.general-form');
    }
}
