<?php

namespace App\Http\Livewire;

use Illuminate\Support\Arr;

abstract class FormWizard extends FormMain
{
    public $steps;
    public $current;
    public $lastStep;
    public $tabs;

    public function mount($params = [])
    {
        parent::mount($params); // TODO: Change the autogenerated stub
        $this->setTabs();
        $this->steps = count($this->tabs);
        $this->current = 1;
        $this->lastStep = 1;
        $this->setTitle($this->tabs[$this->current - 1]);
    }

    public function paginate($type, $fields = [])
    {
        if ($type == 'next' and $this->current < $this->steps) {
            if (count($fields) > 0) {
                $this->rules = [
                    ...$this->rules,
                    ...$this->withCustomValidation(
                        Arr::only(
                            $this->rules(), Arr::whereNotNull($fields)
                        )
                    )
                ];

                $this->validate($this->rules);
            }
            $this->current++;
        } elseif ($type == 'prev' and $this->current > 1) {
            $this->current--;
        }

        $this->setTitle($this->tabs[$this->current - 1]);
    }

    public function moveToTab($index)
    {
        if ($this->editing) {
            $this->current = $index;
        } else {
            if ($this->lastStep < $this->current) {
                $this->lastStep = $this->current;
            }
            if ($index <= $this->lastStep) {
                $this->current = $index;
            }
        }
        $this->setTitle($this->tabs[$this->current - 1]);
    }

    protected function setTabs()
    {
    }

    protected function withCustomValidation($rules)
    {
        return $rules;
    }

}
