<?php

namespace App\Http\Livewire\Payments;

use App\Http\Livewire\FormMain;
use App\Models\Payment;

class Form extends FormMain
{

    protected $model = Payment::class;

    public $props = [
        'contact_id' => null,
        'amount' => null,
        'receipt' => null,
        'note' => null,
        'status' => null,
    ];


    protected function rules(): array
    {
        return [
            'props.amount' => ['required'],
            'props.contact_id' => ['required'],
        ];
    }

    public function mount($params = [])
    {
        parent::mount($params); // TODO: Change the autogenerated stub
        $this->setTitle(__('Create', ['name' => __('Payment')]));
        if ($id = request()->route('payment')) {
            $this->setEditing($id);
            $this->setTitle(__('Edit', ['name' => __('Payment') . ' : ' . $this->editing->contact->name]));
        }
    }

    protected function saveAndRedirect($route = '')
    {
        $route = 'payments.index';
        return parent::saveAndRedirect($route); // TODO: Change the autogenerated stub
    }

    public function render()
    {
        return view('livewire.payments.form');
    }
}
