<?php

namespace App\Http\Livewire\Products;

use App\Http\Livewire\FormMain;
use App\Models\Product;
use Livewire\WithFileUploads;

class Form extends FormMain
{
    use WithFileUploads;

    protected $model = Product::class;

    public $props = [
        'name' => null,
        'description' => null,
    ];

    public $files = [
        'cover' => null,
    ];


    protected function rules(): array
    {
        return [
            'props.name' => ['required', 'string'],
            'files.cover' => ['required'],
        ];
    }

    public function mount($params = [])
    {
        parent::mount($params); // TODO: Change the autogenerated stub
        $this->setTitle(__('Create', ['name' => __('Product')]));

        if ($id = request()->route('product')) {
            $this->setEditing($id);
            $this->setTitle(__('Edit', ['name' => __('Product') . ' : ' . $this->editing->name]));
        }
    }

    protected function validationAttributes(): array
    {
        return [
            'props.name' => __('Name'),
            'files.cover' => __('Cover')
        ];
    }

    protected function saveAndRedirect($route = '')
    {
        $route = 'products.index';
        parent::saveAndRedirect($route); // TODO: Change the autogenerated stub
    }

    public function render()
    {
        return view('livewire.products.form');
    }
}
